### PR TITLE
#33 - bug if you want to login with a username

### PR DESCRIPTION
**Pull request by flashback2k14**
- change registration behavior
  - if registration w/ email, then username is equal to email and Provider is set to Email
  - if registration w/ username, then email is equal to username and Provider is set to Username

### CODE REVIEW

**Comment by hetec** [comment]
Works fine for me! I just added a little fix. But there is still a linter error and I don't know how to fix since it looks fine for me.
test/users.route.test.ts[6, 10]: Named imports must be alphabetized

**Comment by flashback2k14** [comment]
p comes before s ;-)

**Comment by hetec** [comment]
In general I'm still not completely happy with the mechanism of registration. I would prefer a registration where we always require the email address and a password. The username can then be provided additional to the email by the user. If the user provides a name we set the the name if not we use the email as name.

I think it's a bit odd to use the username as email since we cannot send emails to a username and we cannot be sure that we get a email from the user in the future.

What do you think? (Would be the subject of another issue)

**Comment by hetec** [comment]
Ups I looked in the wrong file :)

**Comment by lyio** [comment]
Without having been involved in anything so far, I agree with @hetec. We should always require an email address as that 
1. is our only way to contact the user
2. is the users way to reset their password

**Comment by flashback2k14** [comment]
yes you are right. we should change this.

**Comment by hetec** [comment]
Maybe later, but I can so it

**Comment by flashback2k14** [comment]
Okay, but the bug is fixed. Maybe we should change the behavior with issue #44!?

**Pull request merged**
