### PR TITLE
#1 - bootstrap frontend application

### PR DESCRIPTION
**Pull request by flashback2k14**
angular-cli must be global

```bash
npm install -g angular-cli
```

### CODE REVIEW

**Comment by flashback2k14** [comment]
@lyio @hetec a Short reminder! 😀

**Comment by hetec** [comment]
I will look at this pr tomorrow

**Comment by hetec** [comment]
Looks good at the first glance and runs fine! On thing I don't really understand is why we don't need to use system js as module loader? To my understanding it's because we focus on ES6. Is this correct? If this is the point, we should maybe introduce system js to the project at some point to support older browsers.

**Comment by flashback2k14** [comment]
I think angular-cli and the crazy underlying webpack stuff makes the transpiling to ES5. SystemJS was needed with angular2 Beta releases.

**Pull request merged**
