### PR TITLE
#90 - mongodb fooditem

### PR DESCRIPTION
**Pull request by flashback2k14**
this PR only contains fooditem template logic, endpoints, etc. i think it's enough for one PR. ;-)

### CODE REVIEW

**Comment by flashback2k14** [comment]
@hetec I really start hating travis. Every it's failing and I have no glue why. On my mac everything is running fine.

**Comment by flashback2k14** [comment]
@hetec before you merge PR #89 should we merge this PR. It's created from branch #85.

**Comment by hetec** [comment]
There was a little bug with the save endpoint but I immediately fixed it. The remaining changes look good to me. So maybe you can check my little change and merge this PR.

Q: Does Travis run all tests? I tried to run the tests on my docker mongodb but some of them failed?! But maybe it's because of the docker mongodb

**Comment by flashback2k14** [comment]
Thanks for the bugfix. :-) 

A: yes, travis runs all tests. I haven't tested the docker stuff yet.

**Pull request merged**
